create table if not exists public.players (
  wallet text primary key,
  attempts integer not null default 0 check (attempts >= 0),
  best_distance integer not null default 0 check (best_distance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  transfer_id text not null unique,
  wallet text not null,
  amount_base numeric not null,
  attempts_added integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  wallet text not null,
  distance integer not null check (distance >= 0),
  jump_count integer not null default 0,
  event_log jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists scores_distance_idx on public.scores (distance desc);
create index if not exists scores_wallet_idx on public.scores (wallet);

alter table public.players enable row level security;
alter table public.deposits enable row level security;
alter table public.scores enable row level security;

-- The app uses the Supabase service-role key only in Vercel server functions.
-- No public client-side Supabase key is needed.
